name: Scan Sheet Music

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Requirements
      run: |
        # Tell the server to ignore broken external repositories and force install fluidsynth
        sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm -f /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update --allow-releaseinfo-change || true
        sudo apt-get install -y --fix-missing fluidsynth libraw-dev

    - name: Install AI Libraries
      run: |
        pip install --upgrade pip
        pip install oemer music21

    - name: Run Converter Script
      run: python converter.py
